# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BasicExample

  pod 'mailcore2-ios'

  target 'BasicExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BasicExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BasicExample-tvOS

  target 'BasicExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
