name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build BasicExample
        run: |
          sudo apt-get install lib32stdc++6 lib32z1
          npm i -g yarn
          cd examples/BasicExample
          yarn
          cd android
          ./gradlew assembleDebug
